import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import HeroImage from '../components/HeroImage'

export default function Home({exploreData}) {
  return (
    <div>
      <Head>
        <title>Black~vibes airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroImage />
      <main className='container px-8 sm:px-16 lg:px-20 mx-auto xl:px-6'>
        <section className='pt-6 md:pt-10 lg:pt-16'>
          <h2 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-semibold lg:font-medium">Explore Nearby</h2>
          {exploreData.map(data => (
            <h1>{data.location}</h1>
          ))}
        </section>
      </main>
    </div>
  )
}

export async function getStaticProps(){
  const exploreData = await fetch("links.papareact.com/pyp")
  .then(res => res.json())
  
  return {
    props: {
      exploreData
    }
  }
}
